
//  wpkx_vxcf_sales ->  meta || column data

{
   "fields":{
      "AccountId":{
         "name":"AccountId",
         "type":"Account",
         "label":"Account ID",
         "req":"",
         "maxlength":18,
         "custom":false
      },
      "LastName":{
         "name":"LastName",
         "type":"string",
         "label":"Last Name",
         "req":"true",
         "maxlength":80,
         "custom":false
      },
      "FirstName":{
         "name":"FirstName",
         "type":"string",
         "label":"First Name",
         "req":"",
         "maxlength":40,
         "custom":false
      },
      "Salutation":{
         "name":"Salutation",
         "type":"picklist",
         "label":"Salutation",
         "req":"",
         "maxlength":40,
         "custom":false,
         "options":[
            {
               "active":true,
               "defaultValue":false,
               "label":"Mr.",
               "validFor":null,
               "value":"Mr."
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Ms.",
               "validFor":null,
               "value":"Ms."
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Mrs.",
               "validFor":null,
               "value":"Mrs."
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Dr.",
               "validFor":null,
               "value":"Dr."
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Prof.",
               "validFor":null,
               "value":"Prof."
            }
         ],
         "eg":"Mr.=Mr., Ms.=Ms., Mrs.=Mrs., Dr.=Dr., Prof.=Prof."
      },
      "RecordTypeId":{
         "name":"RecordTypeId",
         "type":"RecordType",
         "label":"Record Type ID",
         "req":"",
         "maxlength":18,
         "custom":false
      },
      "OtherStreet":{
         "name":"OtherStreet",
         "type":"textarea",
         "label":"Other Street",
         "req":"",
         "maxlength":255,
         "custom":false
      },
      "OtherCity":{
         "name":"OtherCity",
         "type":"string",
         "label":"Other City",
         "req":"",
         "maxlength":40,
         "custom":false
      },
      "OtherState":{
         "name":"OtherState",
         "type":"string",
         "label":"Other State\/Province",
         "req":"",
         "maxlength":80,
         "custom":false
      },
      "OtherPostalCode":{
         "name":"OtherPostalCode",
         "type":"string",
         "label":"Other Zip\/Postal Code",
         "req":"",
         "maxlength":20,
         "custom":false
      },
      "OtherCountry":{
         "name":"OtherCountry",
         "type":"string",
         "label":"Other Country",
         "req":"",
         "maxlength":80,
         "custom":false
      },
      "OtherLatitude":{
         "name":"OtherLatitude",
         "type":"double",
         "label":"Other Latitude",
         "req":"",
         "maxlength":0,
         "custom":false
      },
      "OtherLongitude":{
         "name":"OtherLongitude",
         "type":"double",
         "label":"Other Longitude",
         "req":"",
         "maxlength":0,
         "custom":false
      },
      "OtherGeocodeAccuracy":{
         "name":"OtherGeocodeAccuracy",
         "type":"picklist",
         "label":"Other Geocode Accuracy",
         "req":"",
         "maxlength":40,
         "custom":false,
         "options":[
            {
               "active":true,
               "defaultValue":false,
               "label":"Address",
               "validFor":null,
               "value":"Address"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"NearAddress",
               "validFor":null,
               "value":"NearAddress"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Block",
               "validFor":null,
               "value":"Block"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Street",
               "validFor":null,
               "value":"Street"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"ExtendedZip",
               "validFor":null,
               "value":"ExtendedZip"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Zip",
               "validFor":null,
               "value":"Zip"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Neighborhood",
               "validFor":null,
               "value":"Neighborhood"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"City",
               "validFor":null,
               "value":"City"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"County",
               "validFor":null,
               "value":"County"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"State",
               "validFor":null,
               "value":"State"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Unknown",
               "validFor":null,
               "value":"Unknown"
            }
         ],
         "eg":"Address=Address, NearAddress=NearAddress, Block=Block, Street=Street, ExtendedZip=ExtendedZip, Zip=Zip, Neighborhood=Neighborhood, City=City, County=County, State=State, Unknown=Unknown"
      },
      "MailingStreet":{
         "name":"MailingStreet",
         "type":"textarea",
         "label":"Mailing Street",
         "req":"",
         "maxlength":255,
         "custom":false
      },
      "MailingCity":{
         "name":"MailingCity",
         "type":"string",
         "label":"Mailing City",
         "req":"",
         "maxlength":40,
         "custom":false
      },
      "MailingState":{
         "name":"MailingState",
         "type":"string",
         "label":"Mailing State\/Province",
         "req":"",
         "maxlength":80,
         "custom":false
      },
      "MailingPostalCode":{
         "name":"MailingPostalCode",
         "type":"string",
         "label":"Mailing Zip\/Postal Code",
         "req":"",
         "maxlength":20,
         "custom":false
      },
      "MailingCountry":{
         "name":"MailingCountry",
         "type":"string",
         "label":"Mailing Country",
         "req":"",
         "maxlength":80,
         "custom":false
      },
      "MailingLatitude":{
         "name":"MailingLatitude",
         "type":"double",
         "label":"Mailing Latitude",
         "req":"",
         "maxlength":0,
         "custom":false
      },
      "MailingLongitude":{
         "name":"MailingLongitude",
         "type":"double",
         "label":"Mailing Longitude",
         "req":"",
         "maxlength":0,
         "custom":false
      },
      "MailingGeocodeAccuracy":{
         "name":"MailingGeocodeAccuracy",
         "type":"picklist",
         "label":"Mailing Geocode Accuracy",
         "req":"",
         "maxlength":40,
         "custom":false,
         "options":[
            {
               "active":true,
               "defaultValue":false,
               "label":"Address",
               "validFor":null,
               "value":"Address"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"NearAddress",
               "validFor":null,
               "value":"NearAddress"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Block",
               "validFor":null,
               "value":"Block"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Street",
               "validFor":null,
               "value":"Street"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"ExtendedZip",
               "validFor":null,
               "value":"ExtendedZip"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Zip",
               "validFor":null,
               "value":"Zip"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Neighborhood",
               "validFor":null,
               "value":"Neighborhood"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"City",
               "validFor":null,
               "value":"City"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"County",
               "validFor":null,
               "value":"County"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"State",
               "validFor":null,
               "value":"State"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Unknown",
               "validFor":null,
               "value":"Unknown"
            }
         ],
         "eg":"Address=Address, NearAddress=NearAddress, Block=Block, Street=Street, ExtendedZip=ExtendedZip, Zip=Zip, Neighborhood=Neighborhood, City=City, County=County, State=State, Unknown=Unknown"
      },
      "ReportsToId":{
         "name":"ReportsToId",
         "type":"Contact",
         "label":"Reports To ID",
         "req":"",
         "maxlength":18,
         "custom":false
      },
      "Email":{
         "name":"Email",
         "type":"email",
         "label":"Email",
         "req":"",
         "maxlength":80,
         "custom":false
      },
      "Title":{
         "name":"Title",
         "type":"string",
         "label":"Title",
         "req":"",
         "maxlength":128,
         "custom":false
      },
      "Department":{
         "name":"Department",
         "type":"string",
         "label":"Department",
         "req":"",
         "maxlength":80,
         "custom":false
      },
      "AssistantName":{
         "name":"AssistantName",
         "type":"string",
         "label":"Assistant's Name",
         "req":"",
         "maxlength":40,
         "custom":false
      },
      "LeadSource":{
         "name":"LeadSource",
         "type":"picklist",
         "label":"Lead Source",
         "req":"",
         "maxlength":40,
         "custom":false,
         "options":[
            {
               "active":true,
               "defaultValue":false,
               "label":"Web",
               "validFor":null,
               "value":"Web"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Phone Inquiry",
               "validFor":null,
               "value":"Phone Inquiry"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Partner Referral",
               "validFor":null,
               "value":"Partner Referral"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Purchased List",
               "validFor":null,
               "value":"Purchased List"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Other",
               "validFor":null,
               "value":"Other"
            }
         ],
         "eg":"Web=Web, Phone Inquiry=Phone Inquiry, Partner Referral=Partner Referral, Purchased List=Purchased List, Other=Other"
      },
      "Birthdate":{
         "name":"Birthdate",
         "type":"date",
         "label":"Birthdate",
         "req":"",
         "maxlength":0,
         "custom":false
      },
      "Description":{
         "name":"Description",
         "type":"textarea",
         "label":"Contact Description",
         "req":"",
         "maxlength":32000,
         "custom":false
      },
      "OwnerId":{
         "name":"OwnerId",
         "type":"User",
         "label":"Owner ID",
         "req":"",
         "maxlength":18,
         "custom":false
      },
      "HasOptedOutOfEmail":{
         "name":"HasOptedOutOfEmail",
         "type":"boolean",
         "label":"Email Opt Out",
         "req":"",
         "maxlength":0,
         "custom":false
      },
      "HasOptedOutOfFax":{
         "name":"HasOptedOutOfFax",
         "type":"boolean",
         "label":"Fax Opt Out",
         "req":"",
         "maxlength":0,
         "custom":false
      },
      "DoNotCall":{
         "name":"DoNotCall",
         "type":"boolean",
         "label":"Do Not Call",
         "req":"",
         "maxlength":0,
         "custom":false
      },
      "EmailBouncedReason":{
         "name":"EmailBouncedReason",
         "type":"string",
         "label":"Email Bounced Reason",
         "req":"",
         "maxlength":255,
         "custom":false
      },
      "EmailBouncedDate":{
         "name":"EmailBouncedDate",
         "type":"datetime",
         "label":"Email Bounced Date",
         "req":"",
         "maxlength":0,
         "custom":false
      },
      "Jigsaw":{
         "name":"Jigsaw",
         "type":"string",
         "label":"Data.com Key",
         "req":"",
         "maxlength":20,
         "custom":false
      },
      "CleanStatus":{
         "name":"CleanStatus",
         "type":"picklist",
         "label":"Clean Status",
         "req":"",
         "maxlength":40,
         "custom":false,
         "options":[
            {
               "active":true,
               "defaultValue":false,
               "label":"In Sync",
               "validFor":null,
               "value":"Matched"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Different",
               "validFor":null,
               "value":"Different"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Reviewed",
               "validFor":null,
               "value":"Acknowledged"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Not Found",
               "validFor":null,
               "value":"NotFound"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Inactive",
               "validFor":null,
               "value":"Inactive"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Not Compared",
               "validFor":null,
               "value":"Pending"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Select Match",
               "validFor":null,
               "value":"SelectMatch"
            },
            {
               "active":true,
               "defaultValue":false,
               "label":"Skipped",
               "validFor":null,
               "value":"Skipped"
            }
         ],
         "eg":"Matched=In Sync, Different=Different, Acknowledged=Reviewed, NotFound=Not Found, Inactive=Inactive, Pending=Not Compared, SelectMatch=Select Match, Skipped=Skipped"
      },
      "Id":{
         "name":"Id",
         "type":"id",
         "label":"Contact ID",
         "req":"",
         "maxlength":18,
         "custom":false
      }
   }
}

//  wpkx_vxcf_sales ->  data || column data

{
   "map":{
      "LastName":{
         "type":"",
         "value":"",
         "field":"your-name"
      },
      "FirstName":{
         "type":"",
         "value":"",
         "field":"your-subject"
      },
      "Title":{
         "type":"",
         "value":"",
         "field":"your-message"
      }
   },
   "filters":{
      "1":{
         "1":{
            "field":"",
            "op":"is",
            "value":""
         }
      }
   },
   "primary_key":"",
   "primary_key2":"",
   "note_val":"",
   "note_list":""
}